server:
  port: 8080

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  application:
    name: producer-service
  data:
    mongodb:
      uri: mongodb://root:example@mongo:27017/notifications-db?authSource=admin

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    web:
      server:
        auto-time-requests: true



