global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'producer-service-metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'notifications-service'
